### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by ssrlive** [metrics-rs/quanta#101]
Please review it. here is the call stack.

![image](https://github.com/metrics-rs/quanta/assets/30760636/ae679c11-36ba-4eca-931f-156736ac940e)

**Comment by tobz** [comment]
Going to need more information than that. iOS version, device/host processor/rustc version, etc.

**Comment by ssrlive** [comment]
iOS 13.7 - iPhone 7 - rustc version 1.76.0 stable.

**Comment by ssrlive** [comment]
iOS 13.7 - iPhone 7 - rustc version 1.76.0 stable - Xcode 15.2 - macOS Sonoma.

**Comment by ssrlive** [comment]
iOS 13.7 - iPhone 7 - rustc version 1.76.0 stable - Xcode 15.2 - macOS Sonoma x86_64.

**Comment by tobz** [comment]
Just some follow-up links to keep track of the information I found showing that seems to be a limitation on iOS devices:

- https://github.com/tensorflow/tensorflow/issues/29627
- https://github.com/OpenMathLib/OpenBLAS/issues/2281#issuecomment-541154490

**Comment by tobz** [comment]
@ssrlive A fix for this has been released as part of `quanta@v0.12.3`.

You _should_ be able to run `cargo update -p quanta` to pull in the latest version since `moka` doesn't use a pinned version.

Please let me know if that fixes the issue you were seeing.

**Comment by ssrlive** [comment]
test passed.
![image](https://github.com/metrics-rs/quanta/assets/30760636/c59e7fac-0fa8-4c7b-9100-aa7bab2fe4df)

**Comment by tobz** [comment]
Awesome, happy to see it.
