### ISSUE TITLE
Commit for version 0.12.3 it not reachable from main branch

### ISSUE THREAD

**Issue by mcheshkov** [metrics-rs/quanta#103]
I've just picked up new version, and decided to go check the changelog, opened up https://github.com/metrics-rs/quanta/blob/main/CHANGELOG.md, and new version was not there!

It was confusing, even worrisome for a second: what if your credentials was stolen or something like that. Can you please move main branch to 278b3b6 or later? At the moment it is pointing to 8c14d6e

If anyone wonders if 0.12.3 is a geniune release: tag v0.12.3 [is present](https://github.com/metrics-rs/quanta/releases/tag/v0.12.3), and diff between tarballs for [0.12.2](https://static.crates.io/crates/quanta/quanta-0.12.2.crate) and [0.12.3](https://static.crates.io/crates/quanta/quanta-0.12.3.crate) matches with changes in 267effa, 702ea18 and fe3bb3d

**Comment by tobz** [comment]
Ah yeah, good catch.

Looks like I forgot to merge the fix branch into `main`, and released/published from the branch directly. I just merged it and pushed `main`, and everything looks as it should be now.

Thanks again for reporting. 👍🏻
