### ISSUE TITLE
Any plans for ARM support ?

### ISSUE THREAD

**Issue by chris-zen** [metrics-rs/quanta#20]
Do you have any plans for ARM support ? Specially now that Apple is moving to ARM processors.

In case it helps, this is the closest thing I found, but written in C:
https://github.com/google/benchmark/blob/v1.1.0/src/cycleclock.h#L116

**Comment by tobz** [comment]
We currently depend on `std::arch` for stable access to `rdtsc` on x86 platforms.  Adding support to read the Performance Monitor Counters on ARM would require us to drop back down to raw `asm!` calls, and thus nightly.  `quanta` would still fall back to the OS time facilities if a high-speed mode wasn't possible, though.

I personally don't know the performance of OS time facilities on Linux or macOS ARM, so it's hard for me to gauge the value of adding a nightly-only feature when the performance differences might be small.  I'm happy to accept a PR for this support if it's important to you.
