### ISSUE TITLE
Upkeep's Error is not accessible

### ISSUE THREAD

**Issue by antifuchs** [metrics-rs/quanta#21]
I'm finally getting around to updating `governor` to use quanta 0.6.0 - unfortunately, it looks like the `Error` that `Upkeep` starting returns is not accessible (it's in a private mod, but not `pub use`d in lib.rs), so can't be used in function signatures. 

Could you publicly export it?

**Comment by tobz** [comment]
Ooh, woops!

Let me fix that. :)

**Comment by tobz** [comment]
All set: fixed in `quanta@0.6.1`.
