### ISSUE TITLE
does not build on MIPS

### ISSUE THREAD

**Issue by nazar554** [metrics-rs/quanta#22]
I can't build `quanta 0.3.1` with `mipsel-unknown-linux-musl` target. Should it still build and fallback to OS facilities?
Is there any workaround to use it with `metrics-runtime`?

Found [this ](https://doc.rust-lang.org/std/sync/atomic/#portability)in docs for `std::sync::atomic`:

> PowerPC and MIPS platforms with 32-bit pointers do not have AtomicU64 or AtomicI64 types.

 

```
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
  --> /cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.3.1/src/lib.rs:51:14
   |
51 |     atomic::{AtomicU64, Ordering},
   |              ^^^^^^^^^
   |              |
   |              no `AtomicU64` in `sync::atomic`
   |              help: a similar name exists in the module: `AtomicU8`

error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
 --> /cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.3.1/src/mock.rs:5:18
  |
5 |         atomic::{AtomicU64, Ordering},
  |                  ^^^^^^^^^
  |                  |
  |                  no `AtomicU64` in `sync::atomic`
  |                  help: a similar name exists in the module: `AtomicU8`

error: aborting due to 2 previous errors
```

**Comment by tobz** [comment]
I'll see if I can backport your PR to an 0.3 version of `quanta` and potentially do a patch release to help ya out.

**Comment by nazar554** [comment]
I have a [feature/atomic-shim-0.3.1](https://github.com/nazar554/quanta/tree/feature/atomic-shim-0.3.1) branch in my fork, it seems to build already. I addeda `#[ctor]` [hack ](https://github.com/nazar554/quanta/commit/4485d6e7699a9fa46971aa5417c6d47790036262)for static initializtion of `AtomicU64`

**Comment by tobz** [comment]
Nice.  I created a branch, `0.3-lts`, based off of the 0.3.1 commit.  If you want to submit that feature branch as a PR, based against the LTS branch, we can get that going as well, and hopefully released quickly.

**Comment by messense** [comment]
```
   Compiling quanta v0.9.2
error[E0599]: no method named `fetch_add` found for struct `Arc<AtomicCell<u64>>` in the current scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.9.2/src/mock.rs:48:21
   |
48 |         self.offset.fetch_add(amount.into_nanos());
   |                     ^^^^^^^^^ method not found in `Arc<AtomicCell<u64>>`

error[E0599]: no method named `fetch_sub` found for struct `Arc<AtomicCell<u64>>` in the current scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.9.2/src/mock.rs:53:21
   |
53 |         self.offset.fetch_sub(amount.into_nanos());
   |                     ^^^^^^^^^ method not found in `Arc<AtomicCell<u64>>`

error: aborting due to 2 previous errors
```

**Comment by nazar554** [comment]
@messense `crossbeam` disables 64-bit atomics on unsupported platforms (with `crossbeam_no_atomic_64` feature) 
See https://github.com/crossbeam-rs/crossbeam/issues/731

Can be fixed by not using `crossbeam` on MIPS & PowerPC, or implementing support for atomic_shim there as well
