### ISSUE TITLE
TSC always disabled on AMD

### ISSUE THREAD

**Issue by robsmith11** [metrics-rs/quanta#25]
I wanted to use quanta on my AMD Ryzen 4700u laptop with linux, but it seems that `has_constant_or_better_tsc` always returns `false` on AMD hardware because of the check `has_multiple_sockets` is hard-coded to return `true`.  `read_cpuid_nonstop_tsc` returns the correct result, but that check is never reached.

I've forced constant TSC support and quanta successfully calibrates and seems to be working fine, so the fix should maybe be to trust the result of `read_cpuid_nonstop_tsc`.

**Comment by tobz** [comment]
So, long story short: I'm going to go ahead and remove the `has_multiple_sockets` check, which should unblock you.

The backstory is that, if you do some spelunking in the Linux kernel code, there's a blurb in the TSC code that essentially says: "we're not sure if platforms other than Intel synchronize multiple sockets to each other, and so we can't be sure that TSC will be synchronized."

I think we're probably OK for the moment to assume that older/esoteric hardware won't be a big issue given how rare it is, and I had mostly put in the `has_multiple_sockets` function with the intention to properly detect multiple sockets, etc... which I've clearly been slacking on.

**Comment by tobz** [comment]
Released `quanta@0.6.3` which incorporates this change.  Happy hunting!
