### ISSUE TITLE
CLOCK_REALTIME support? 

### ISSUE THREAD

**Issue by robsmith11** [metrics-rs/quanta#27]
I'm curious what your thoughts are on adding CLOCK_REALTIME support as a very fast way to get calibrated wall-clock time from the TSC.

My initial use-case is on an AMD system where faulty firmware has caused Linux to fall back to the slow HPET, despite it seemingly possible to get good enough results from the TSC.  But it may be nice just to avoid get_clocktime overhead in other cases too.

I switched the clock myself, and the calibration looks good but maybe I'm missing something.

**Comment by tobz** [comment]
If we add support for this by, say, adding a new method for creating a `Clock` with a `CLOCK_REALTIME` reference (call it `with_wall_clock_time` or whatever), then we also have to add it for other platforms.

My bar for things in this library is "can we do it for Windows, macOS, _and_ Linux?".

Beyond that, though, there's a very good chance that `Instant::as_u64` gets tossed before a 1.0 release, which means `Instant` will be just as opaque as `std::time::Instant`, leaving it unsuitable for actually displaying wall-clock time.

So, overall, I think that if we can come up with some sort of working example of a 1) new method for getting wall-clock time (like `now` but `wall_clock` instead) that 2) returns something other than `Instant` (probably a `SystemTime` clone) and 3) has support for all three major platforms, then I would definitely be receptive to reviewing and very likely merging it.

**Comment by tobz** [comment]
Going to close this as most of the recent changes to the crate have centered around moving away from providing any sort of absolute measurement of time, and focusing solely on measuring the _passage_ of time instead.

We won't add back ways to actually get at the raw measurements for use as wall-clock time (even though we, effectively, measuring the _passage_ of wall-clock time) and as such, adding support for another clock would not make sense as we only care about using it as a calibration reference.
