### ISSUE TITLE
Attempting to start Upkeep always returns an UpkeepRunning error

### ISSUE THREAD

**Issue by alexhexabeam** [metrics-rs/quanta#28]
Even given the below minimal example:
```rust
use quanta::Upkeep;
use std::time::Duration;

fn main() {
    Upkeep::new(Duration::from_millis(250)).start().unwrap();
}
```

This will fail with:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UpkeepRunning', src/main.rs:5:5
```

There are no other threads, and I have not started another Upkeep.
Perhaps I am just using it wrong, but there aren't any examples. I apologize if this ticket is erroneous.

This is with quanta 0.6.4, tested on Mac OSX.

**Comment by tobz** [comment]
You're definitely right!  I'm addressing this in #29.

**Comment by tobz** [comment]
Release `quanta@0.6.5` with this fix.

Thanks again for reporting!
