### ISSUE TITLE
Allow Instant to be used atomically

### ISSUE THREAD

**Issue by jean-airoldie** [metrics-rs/quanta#70]
I have a use case in a rate limiter where I need an atomic instant. There are to solutions that I can think of:

* Add the ability for the user to convert the instant into and from a raw u64. I think this ability used to exist but was removed (as_unix_duration).
* Add a AtomicInstant value that inputs and outputs Instant with a load and set method etc.

Currently a user can transmute the Instant into u64 to emulate the first solution, however this is unsound obviously.

**Comment by jean-airoldie** [comment]
Nevermind, since there is no longer a way to convert Instant into a std::time::Duration, I can't use this crate anyway.

**Comment by tobz** [comment]
> Nevermind, since there is no longer a way to convert Instant into a std::time::Duration, I can't use this crate anyway.

I'm curious: in what situation would you want to convert a `Instant` as-is to a `Duration`? What's the result you expect from doing that?

**Comment by jean-airoldie** [comment]
I was using `Instant::as_unix_duration` and then converting that into a system time by doing the whole UNIX_EPOCH + Duration thing, but I understand that this isn't expected behavior since the Instant this crate provides can't really be mapped to an accurate system time. If that's the case then removing `Instant::as_unix_duration` front your API seems like a good call because I was misusing the API. Now I'm just using SystemTime -> Duration::as_nanos -> AtomicU64.
