### ISSUE TITLE
Types for measurements?

### ISSUE THREAD

**Issue by antifuchs** [metrics-rs/quanta#8]
I'm looking into Quanta for a clock implementation in my library, and am somewhat confused how to safely use it, especially with the optimized clock methods that all return `u64`. 

To help me understand the various interconnected pieces, I made the following - maybe it's useful for somebody, or maybe it can be included in quanta as a module?

``` rust
#![cfg_attr(feature = "cargo-clippy", deny(warnings))]

use std::sync::Arc;
use std::time::Duration;

#[repr(transparent)]
pub struct RawMeasurement(u64);

impl RawMeasurement {
    pub unsafe fn raw_value(&self) -> u64 {
        self.0
    }
}

#[repr(transparent)]
pub struct ReferenceTime(u64);

impl ReferenceTime {
    pub fn to_nanos(&self) -> u64 {
        self.0
    }

    pub fn to_duration(&self) -> Duration {
        Duration::from_nanos(self.0)
    }
}

#[repr(transparent)]
pub struct Clock(quanta::Clock);

impl Clock {
    pub fn new() -> Clock {
        Clock(quanta::Clock::new())
    }

    pub fn mock() -> (Clock, Arc<quanta::Mock>) {
        let (qc, mock) = quanta::Clock::mock();
        (Clock(qc), mock)
    }

    pub fn now(&self) -> ReferenceTime {
        ReferenceTime(self.0.now())
    }

    pub fn start(&self) -> RawMeasurement {
        RawMeasurement(self.0.start())
    }

    pub fn end(&self) -> RawMeasurement {
        RawMeasurement(self.0.end())
    }

    pub fn scaled(&self, raw: RawMeasurement) -> ReferenceTime {
        ReferenceTime(self.0.scaled(raw.0))
    }

    pub fn delta(&self, start: RawMeasurement, end: RawMeasurement) -> ReferenceTime {
        ReferenceTime(self.0.delta(start.0, end.0))
    }

    pub fn recent(&self) -> ReferenceTime {
        ReferenceTime(self.0.recent())
    }
}

```

Main questions are:
* Is the type structure above correct?
* Is that even useful?

**Comment by tobz** [comment]
@antifuchs This is obviously so long ago, but... I just released v0.4.0 which now outputs all reference time-scaled values as a new type: `quanta::Instant`, which provides some level of compatibility with the existing `std::time` API.

Source time-scaled values are still raw `u64`, but hopefully this makes it easier to avoid pitfalls, as well as makes some of the typical use cases -- like comparing the delta between two measurements against a constant `Duration`, etc -- easier to accomplish.
