### ISSUE TITLE
RUSTSEC-2020-0168: mach is unmaintained

### ISSUE THREAD

**Issue by vbrandl** [metrics-rs/quanta#80]
I have a project, that indirectly depends on `quanta` through [`metrics-exporter-prometheus`](https://crates.io/crates/metrics-exporter-prometheus). The `mach` dependency, on which `quanta` depends, is unmaintained: https://rustsec.org/advisories/RUSTSEC-2020-0168.html

There is a fork of `mach`, that might be an alternative: https://crates.io/crates/mach2

 While the project does not run on iOS or MacOS, I would prefer to know the problem is fixed instead of suppressing this advisory.

**Comment by tobz** [comment]
There's an open PR for this -- #79 -- that I haven't taken a look at yet. It's still not super clear to me why they marked the crate as unmaintained as RUSTSEC, like if there was an _actual_ problem, or problems, vs simply being unmaintained.

Figuring that out is the first step before I merge the aforementioned PR.

**Comment by tobz** [comment]
Resolved as #79 has now been released as of `quanta@v0.11.0`.
