### ISSUE TITLE
Much slower than std version in case of high contention

### ISSUE THREAD

**Issue by loyd** [metrics-rs/quanta#81]
Hello, thanks for the crate.

We simultaneously use `Instant::now()` from multiple cores for our metrics. We noticed that `Instant::now()` consumes a lot of CPU cycles (actually, TOP-1 in our perf), so we tried to replace it with `std::time::Instant`, and it performs much better.

The problem is that `quanta` updates one global atomic every time, which leads to massive contention:
https://github.com/metrics-rs/quanta/blob/3a7d361b3cfa7553cc668cc2ecfb444dad29b79f/src/lib.rs#L359-L361

After removing this code (we don't have problems with decreasing rdtsc in our case), `quanta` outperforms `std::time::Instant` again.

Std version [doesn't try](https://doc.rust-lang.org/stable/std/time/struct.Instant.html#monotonicity) to handle violation of monotonicity in `now()`, instead it's saturating to zero in `sub`, `duration_since` and `elapsed`. Should `quanta` follow this way and avoid contention on the global atomic? Or, at least, it should store the atomic in TLS. What do you think about it all?

**Comment by loyd** [comment]
For [elfo](https://github.com/elfo-rs/elfo)'s benches (`Instant::now()` is called on every sent messages).

* `master` uses the main branch of `quanta`.
* `quanta-no-atomic` is `quanta` without the `last` atomic.

```
group                                       master                                    quanta-no-atomic
-----                                       ------                                    ----------------
only_command/one_to_one/one_instance/1      1.01  385.7±150.81ns  2.5 MElem/sec       1.00  381.8±139.82ns  2.5 MElem/sec
only_command/one_to_one/one_instance/10     1.00  1858.9±374.52ns  5.1 MElem/sec      1.00  1851.1±365.30ns  5.2 MElem/sec
only_command/one_to_one/one_instance/11     1.00      2.0±0.35µs  5.1 MElem/sec       1.04      2.1±0.41µs  4.9 MElem/sec
only_command/one_to_one/one_instance/12     1.00      2.2±0.46µs  5.1 MElem/sec       1.01      2.3±0.44µs  5.0 MElem/sec
only_command/one_to_one/one_instance/2      1.00  667.7±223.61ns  2.9 MElem/sec       1.05  703.6±197.88ns  2.7 MElem/sec
only_command/one_to_one/one_instance/3      1.05  819.2±218.26ns  3.5 MElem/sec       1.00  778.5±194.45ns  3.7 MElem/sec
only_command/one_to_one/one_instance/4      1.04  972.5±219.04ns  3.9 MElem/sec       1.00  937.8±214.11ns  4.1 MElem/sec
only_command/one_to_one/one_instance/5      1.03  1117.7±215.19ns  4.3 MElem/sec      1.00  1089.4±202.79ns  4.4 MElem/sec
only_command/one_to_one/one_instance/6      1.04  1241.7±298.23ns  4.6 MElem/sec      1.00  1188.3±238.32ns  4.8 MElem/sec
only_command/one_to_one/one_instance/7      1.03  1415.1±304.17ns  4.7 MElem/sec      1.00  1369.2±239.85ns  4.9 MElem/sec
only_command/one_to_one/one_instance/8      1.02  1559.9±288.44ns  4.9 MElem/sec      1.00  1528.8±272.52ns  5.0 MElem/sec
only_command/one_to_one/one_instance/9      1.01  1748.4±325.39ns  4.9 MElem/sec      1.00  1723.1±367.88ns  5.0 MElem/sec
only_command/round_robin/one_instance/1     1.00  368.7±129.81ns  2.6 MElem/sec       1.04  383.9±125.87ns  2.5 MElem/sec
only_command/round_robin/one_instance/10    1.13      2.9±0.41µs  3.3 MElem/sec       1.00      2.5±0.39µs  3.7 MElem/sec
only_command/round_robin/one_instance/11    1.03      3.0±0.47µs  3.5 MElem/sec       1.00      2.9±0.46µs  3.6 MElem/sec
only_command/round_robin/one_instance/12    1.01      3.1±0.59µs  3.6 MElem/sec       1.00      3.1±0.49µs  3.7 MElem/sec
only_command/round_robin/one_instance/2     1.13  1002.3±290.06ns 1948.7 KElem/sec    1.00  886.3±277.68ns  2.2 MElem/sec
only_command/round_robin/one_instance/3     1.02  1159.7±292.92ns  2.5 MElem/sec      1.00  1136.9±268.56ns  2.5 MElem/sec
only_command/round_robin/one_instance/4     1.01  1472.2±280.06ns  2.6 MElem/sec      1.00  1458.7±310.67ns  2.6 MElem/sec
only_command/round_robin/one_instance/5     1.04  1769.2±354.18ns  2.7 MElem/sec      1.00  1701.6±389.77ns  2.8 MElem/sec
only_command/round_robin/one_instance/6     1.04      2.0±0.35µs  2.8 MElem/sec       1.00  1943.5±395.19ns  2.9 MElem/sec
only_command/round_robin/one_instance/7     1.04      2.3±0.41µs  2.9 MElem/sec       1.00      2.2±0.41µs  3.1 MElem/sec
only_command/round_robin/one_instance/8     1.04      2.5±0.41µs  3.0 MElem/sec       1.00      2.4±0.51µs  3.1 MElem/sec
only_command/round_robin/one_instance/9     1.00      2.6±0.39µs  3.4 MElem/sec       1.01      2.6±0.50µs  3.3 MElem/sec
```

So, 0-13% difference.

It's only about one `Instant::now()`. In practice, with telemetry, the situation is much worse (up to 50% of cycles on our production setup).

**Comment by tobz** [comment]
👋🏻 

This mattered more when `Instant::as_u64` still existed for getting the raw `u64` measurement value. Given that `Instant::as_u64` has been removed, though, I like your idea of mirroring what `std::time::Instant` does, handling monotonicity violations in the addition/subtraction methods and traitg impls directly.

I'm open to reviewing a PR which makes that change; life is a bit busy at the moment so it'd likely take a lot longer for me to get around to doing it myself.
