### ISSUE TITLE
core::arch ?

### ISSUE THREAD

**Issue by sebastiencs** [metrics-rs/quanta#9]
Hi,

I was looking for a timing library on crates.io and saw quanta.
I am wondering why you are not using the module `core::arch` ?

It is available on stable rust and the instruction `rdtsc` is there:
https://doc.rust-lang.org/core/arch/x86_64/fn._rdtsc.html

**Comment by tobz** [comment]
No particular reason!

I was playing with the original code back before `std::arch` was stabilized, didn't update the code once it was available, and then pushed this crate into the world and sort of forgot about using `std::arch`.

Happy to accept a PR or leave this issue open as a reminder to switch over to `std::arch` in the next few weeks (busy at work).
